# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for deploying models to ACI

parameters:
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: amlWorkspaceName
  type: string
- name: groupingTags
  type: string


jobs:

- job: deploy_models
  displayName: 'Deploy Models'
  steps:

        - task: UsePythonVersion@0
          displayName: 'Use Python 3.7'
          inputs:
            versionSpec: 3.7

        - task: AzureCLI@1
          displayName: 'Deploy Models in Groups'
          inputs:
            azureSubscription: $(SERVICECONNECTION_WORKSPACE)
            scriptLocation: inlineScript
            inlineScript: |
              # Install dependencies
              python -m pip install --upgrade pip && python -m pip install joblib azureml-sdk
              # Create/update training pipeline
              python scripts/deploy_grouped_models.py --grouping-tags ${{parameters.groupingTags}} \
                                                      --endpoints-path 'endpoints.pkl' \
                                                      --subscription-id $(az account show --query id -o tsv) \
                                                      --resource-group $(RESOURCE_GROUP) \
                                                      --workspace-name $(AMLWORKSPACE_NAME)

        - publish: 'endpoints.pkl'
          artifact: endpointsartifact
          displayName: 'Publish Endpoints Artifact'
                             