# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that configures the environment for this solution accelerator

trigger:
  branches:
    include:
    - feature/mlops
  paths:
    include:
    - mlops_pipelines/1-setup/*

variables:
- group: manymodels-vg
- template: ../many-models-variables.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: deploy_infra
  displayName: 'Deploy Infra'
  jobs:
  - template: deploy-infra/deploy-infra.template.yml
    parameters:
      serviceConnection: '$(SERVICECONNECTION_GROUP)'

- stage: environment_setup
  displayName: 'Environment Setup'
  jobs:
  - template: environment-setup/environment-setup.template.yml
