# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for running the training pipeline

parameters:
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: amlWorkspaceName
  type: string
- name: trainingPipelineName
  type: string


jobs:

- job: pipeline_id
  displayName: 'Get Training Pipeline ID'
  steps:

    - task: AzureCLI@1
      name: get_pipeline_id
      displayName: 'Get Training Pipeline ID'
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptLocation: inlineScript
        inlineScript: |
          # Install ML extension
          az extension add -n azure-cli-ml
          # Get training pipeline ID
          workspace_params="--workspace-name ${{parameters.amlWorkspaceName}} --resource-group ${{parameters.resourceGroup}}"
          pipeline_id=$(az ml pipeline list $workspace_params --query "[?Name == '${{parameters.trainingPipelineName}}'].Id" -o tsv)
          echo "##vso[task.setvariable variable=pipeline_id;isOutput=true;]$pipeline_id"

- job: run_training
  displayName: 'Run Training'
  pool: server
  dependsOn: pipeline_id
  variables: 
    pipeline_id: $[ dependencies.pipeline_id.outputs['get_pipeline_id.pipeline_id'] ]
  steps:

    - task: ms-air-aiagility.vss-services-azureml.azureml-restApi-task.MLPublishedPipelineRestAPITask@0
      displayName: 'Invoke AML Training Pipeline'
      inputs:
        azureSubscription: '${{parameters.serviceConnection}}'
        PipelineId: '$(PIPELINE_ID)'
        ExperimentName: '${{parameters.trainingPipelineName}}'


