# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that runs AML Pipeline for model training

trigger:
  branches:
    include:
    - feature/mlops
  paths:
    include:
    - mlops_pipelines/3-modeling/*

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily training at midnight'
  branches:
    include:
    - feature/mlops
  always: true

variables:
- group: manymodels-vg
- template: ../many-models-variables.yml

pool:
  vmImage: ubuntu-latest

stages:

# - stage: update_data
#   displayName: 'Update Data for Training'
#   jobs:
#   - template: update-data/update-data.template.yml

- stage: run_training
  displayName: 'Run Model Training'
  jobs:
  - template: run-training/run-training.template.yml
    parameters:
      serviceConnection: '$(SERVICECONNECTION_WORKSPACE)'
      resourceGroup: '$(RESOURCE_GROUP)'
      amlWorkspaceName: '$(AMLWORKSPACE_NAME)'
      trainingPipelineName: '$(AML_TRAINING_PIPELINE_NAME)'

- stage: deploy_models_aci
  displayName: 'Deploy Models to ACI'
  jobs:
  - template: deploy-models-aci/deploy-models-aci.template.yml
    parameters:
      serviceConnection: '$(SERVICECONNECTION_WORKSPACE)'
      resourceGroup: '$(RESOURCE_GROUP)'
      amlWorkspaceName: '$(AMLWORKSPACE_NAME)'
      groupingTags: '$(AML_MODEL_GROUPING_TAGS)'
      routingModelName: '$(AML_ROUTING_MODEL_NAME)'
      routingModelTagName: '$(AML_ROUTING_MODEL_TAG_NAME)'
      routingModelTagValue: '$(AML_ROUTING_MODEL_TAG_VALUE)'
      routingServiceName: '$(AML_ROUTING_WEBSERVICE)'

# - stage: deploy_models-aks
#   displayName: 'Deploy Models to AKS'
#   jobs:
#   - template: deploy-models-aks/deploy-models-aks.template.yml
