# Azure Pipeline Template for ML Workspace Resources Deployment
parameters:
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: resourcesLocation
  type: string

jobs:
- deployment: DeployAMLResources
  displayName: Deploy AML Resources
  pool:
    vmImage: ubuntu-16.04
  environment: environment
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: infratemplates

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Storage Account for AML'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: ${{ parameters.resourcesLocation }}
            csmFile: '$(Pipeline.Workspace)/infratemplates/storage/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/storage/parameters.json'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Container Registry'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: ${{ parameters.resourcesLocation }}
            csmFile: '$(Pipeline.Workspace)/infratemplates/containerregistry/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/containerregistry/parameters.json'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Application Insights'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: ${{ parameters.resourcesLocation }}
            csmFile: '$(Pipeline.Workspace)/infratemplates/appinsights/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/appinsights/parameters.json'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Key Vault'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: ${{ parameters.resourcesLocation }}
            csmFile: '$(Pipeline.Workspace)/infratemplates/keyvault/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/keyvault/parameters.json'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy ML Workspace'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: ${{ parameters.resourcesLocation }}
            csmFile: '$(Pipeline.Workspace)/infratemplates/mlworkspace/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/mlworkspace/parameters.json'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy ML Compute'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: ${{ parameters.resourcesLocation }}
            csmFile: '$(Pipeline.Workspace)/infratemplates/mlcompute/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/mlcompute/parameters.json'
