# Azure Pipeline Definition for Infrastructure Deployment

# Trigger on changes in the infrastructure folder and on the master branch                      
trigger:
  branches:
    include:
    - feature/mlops

  paths:
    include:
    - MLOps/infra-as-code/*

stages:
- stage: Build
  displayName: 'IaC Build'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: 'MLOps/infra-as-code/arm-templates'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: infratemplates

- stage: Infra
  displayName: 'Infra Deployment'
  jobs:
  - template: deploy-infra.template.yml
    parameters:
      serviceConnection: '$(serviceConnection)'
      resourceGroup: '$(resourceGroup)'
      resourcesLocation: '$(resourcesLocation)'
