# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for ML Workspace Resources Deployment

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: resourcesLocation
  type: string
- name: storageAccountName
  type: string

jobs:

- job: iac_build
  displayName: 'IaC Build'
  steps:
  - task: CopyFiles@2
    displayName: 'Copy ARM templates'
    inputs:
      sourceFolder: 'mlops_pipelines/1-setup/deploy-infra/arm-templates'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - publish: '$(Build.ArtifactStagingDirectory)'
    artifact: infratemplates


- deployment: DeployAMLResources
  displayName: Deploy AML Resources
  environment: ${{parameters.environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: infratemplates
        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Storage Account'
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            resourceGroupName: ${{parameters.resourceGroup}}
            location: ${{parameters.resourcesLocation}}
            csmFile: '$(Pipeline.Workspace)/infratemplates/storage/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/infratemplates/storage/parameters.json'
            overrideParameters: '-name ${{parameters.storageAccountName}} -location ${{parameters.resourcesLocation}}'
